### ISSUE TITLE
Invalid email address

### ISSUE THREAD

**Issue by kernelr0p** [CyberCX-STA/PurpleOps#17]
Everything was running fine until today while login to the application, we are getting the following error message:
![Screenshot 2024-04-15 at 11 22 41](https://github.com/CyberCX-STA/PurpleOps/assets/101555349/377e7542-c128-4d63-b4ca-67209f52c76c)
Only few users were added on top of the admin user but nobody can login to the application.
Log of the docker-compose:
```
[+] Running 2/0
 ✔ Container mongodb    Created                                                                                                                        0.0s
 ✔ Container purpleops  Created                                                                                                                        0.0s
Attaching to mongodb, purpleops
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.544+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.545+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"main","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":21},"outgoing":{"minWireVersion":6,"maxWireVersion":21},"isInternalClient":true}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.549+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.551+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","namespace":"config.tenantMigrationDonors"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.551+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","namespace":"config.tenantMigrationRecipients"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.551+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.551+00:00"},"s":"I",  "c":"TENANT_M", "id":7091600, "ctx":"main","msg":"Starting TenantMigrationAccessBlockerRegistry"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.552+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"e26aedd34ade"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.552+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"7.0.8","gitVersion":"c5d33e55ba38d98e2f48765ec4e55338d67a4a64","openSSLVersion":"OpenSSL 3.0.2 15 Mar 2022","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2204","distarch":"x86_64","target_arch":"x86_64"}}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.552+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"22.04"}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.552+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.554+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.555+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
mongodb    | {"t":{"$date":"2024-04-15T09:02:02.555+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3466M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,remove=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=2000),statistics_log=(wait=0),json_output=(error,message),verbose=[recovery_progress:1,checkpoint_progress:1,compact_progress:1,backup:0,checkpoint:0,compact:0,evict:0,history_store:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],"}}
purpleops  | Waiting for Mongo...
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.956+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":1401}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.956+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.972+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.972+00:00"},"s":"W",  "c":"CONTROL",  "id":5123300, "ctx":"initandlisten","msg":"vm.max_map_count is too low","attr":{"currentValue":65530,"recommendedMinimum":1677720,"maxConns":838860},"tags":["startupWarnings"]}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.976+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":21},"outgoing":{"minWireVersion":6,"maxWireVersion":21},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":21,"maxWireVersion":21},"outgoing":{"minWireVersion":21,"maxWireVersion":21},"isInternalClient":true}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.976+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersion":"7.0","context":"startup"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.976+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.986+00:00"},"s":"I",  "c":"CONTROL",  "id":6608200, "ctx":"initandlisten","msg":"Initializing cluster server parameters from disk"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.986+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.987+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.991+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.991+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.993+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.993+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.993+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:03.994+00:00"},"s":"I",  "c":"CONTROL",  "id":8423403, "ctx":"initandlisten","msg":"mongod startup complete","attr":{"Summary of time elapsed":{"Startup from clean shutdown?":true,"Statistics":{"Transport layer setup":"0 ms","Run initial syncer crash recovery":"0 ms","Create storage engine lock file in the data directory":"0 ms","Get metadata describing storage engine":"0 ms","Validate options in metadata against current startup options":"0 ms","Create storage engine":"1413 ms","Write current PID to file":"0 ms","Initialize FCV before rebuilding indexes":"4 ms","Drop abandoned idents and get back indexes that need to be rebuilt or builds that need to be restarted":"0 ms","Rebuild indexes for collections":"0 ms","Load cluster parameters from disk for a standalone":"0 ms","Build user and roles graph":"0 ms","Set up the background thread pool responsible for waiting for opTimes to be majority committed":"0 ms","Initialize information needed to make a mongod instance shard aware":"0 ms","Start up the replication coordinator":"3 ms","Start transport layer":"0 ms","_initAndListen total elapsed time":"1441 ms"}}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:04.044+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50400","uuid":{"uuid":{"$uuid":"ef76a76d-e7ff-471e-9f1d-d8066ea17674"}},"connectionId":1,"connectionCount":1}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:04.045+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.18.0.3:50400","uuid":{"uuid":{"$uuid":"ef76a76d-e7ff-471e-9f1d-d8066ea17674"}},"connectionId":1,"connectionCount":0}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.175+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50402","uuid":{"uuid":{"$uuid":"51d1cc24-76fb-431f-aeb2-c4e754cbf068"}},"connectionId":2,"connectionCount":1}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.175+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.18.0.3:50402","client":"conn2","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-1046-oracle"},"platform":"CPython 3.11.3.final.0"}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.177+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50404","uuid":{"uuid":{"$uuid":"7dfc64f4-ad15-4d4b-8239-61ec2dc99ebf"}},"connectionId":3,"connectionCount":2}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.177+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50406","uuid":{"uuid":{"$uuid":"116fca7f-ca8a-425a-a5a0-4276fb21df4f"}},"connectionId":4,"connectionCount":3}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.178+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"172.18.0.3:50406","client":"conn4","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-1046-oracle"},"platform":"CPython 3.11.3.final.0"}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.179+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"172.18.0.3:50404","client":"conn3","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-1046-oracle"},"platform":"CPython 3.11.3.final.0"}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.180+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn3","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":0}}

                                           mongodb    | {"t":{"$date":"2024-04-15T09:02:06.679+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn2","msg":"Interrupted operation as its client disconnected","attr":{"opId":40}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.681+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"172.18.0.3:50402","uuid":{"uuid":{"$uuid":"51d1cc24-76fb-431f-aeb2-c4e754cbf068"}},"connectionId":2,"connectionCount":2}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.791+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn4","msg":"Connection ended","attr":{"remote":"172.18.0.3:50406","uuid":{"uuid":{"$uuid":"116fca7f-ca8a-425a-a5a0-4276fb21df4f"}},"connectionId":4,"connectionCount":1}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:06.792+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn3","msg":"Connection ended","attr":{"remote":"172.18.0.3:50404","uuid":{"uuid":{"$uuid":"7dfc64f4-ad15-4d4b-8239-61ec2dc99ebf"}},"connectionId":3,"connectionCount":0}}
purpleops  | [2024-04-15 09:02:07 +0000] [1] [INFO] Starting gunicorn 20.1.0
purpleops  | [2024-04-15 09:02:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
purpleops  | [2024-04-15 09:02:07 +0000] [1] [INFO] Using worker: sync
purpleops  | [2024-04-15 09:02:07 +0000] [33] [INFO] Booting worker with pid: 33

                                           mongodb    | {"t":{"$date":"2024-04-15T09:02:08.878+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50408","uuid":{"uuid":{"$uuid":"c7314796-736a-4264-b6c7-92cf6763583f"}},"connectionId":5,"connectionCount":1}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:08.881+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"172.18.0.3:50408","client":"conn5","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-1046-oracle"},"platform":"CPython 3.11.3.final.0"}}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:08.888+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:50410","uuid":{"uuid":{"$uuid":"ab1a611d-412b-43d0-b6b9-b069641ec641"}},"connectionId":6,"connectionCount":2}}
mongodb    | {"t":{"$date":"2024-04-15T09:02:08.890+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"172.18.0.3:50410","client":"conn6","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-1046-oracle"},"platform":"CPython 3.11.3.final.0"}}}
```
Worst case scenario, how can I export the content of the assessment to a fresh instance manually?. Is it possible to disable the authentication temporarily?.
Regards.

**Comment by OtherPeoplesEnemy** [comment]
Not sure if a recent update broke login but It was working before for me with no issues had to do a fresh install now I am getting this  error.  I am  using the email and password created for me.

**Comment by joda32** [comment]
So I suspect someone broke the code but not our code (well i believe so).
it looks like there was a upstream change in one of the flask-security
dependencies and it looked like on login it caused a dns lookup for
purpleops.com's MX that doesn't exist and it should never have done this.

I've added this to the flask.cfg file

{"check_deliverability": False}

And it seems to have fixed it in the lab at least. I've pushed it to GIT so
please blow the old docker images away, update from git and try again.and
please let me know if it work.

Also, thanks for the bug report :)

**Comment by kernelr0p** [comment]
I have tried to do a fresh install and it works but if i blow the old docker images away and update from git, im still getting the same error. 

1. sudo docker rm -vf $(sudo docker ps -a -q)
2. sudo docker rmi -f $(sudo docker images -a -q)
3. docker system prune -a
Pulling the repo from git and running docker compose up will retrieve mongo and purpleops images but won't detect a new instance, not creating new user/passwords to login. If i re-type previous creds, it throws the same error.
